<?php

namespace App\Services\v1;

use App\Jobs\FileMergeChunks;
use App\Jobs\FileScan;
use App\Models\File;
use App\Models\Upload;
use App\Models\User;
use Exception;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

class UploadCompleteService
{
    public function __construct(
        private AuthService $authService,
        private FileStorageService $fileStorageService
    ) {
        // 
    }

    /**
     * Process file and complete upload.
     * 
     * @param \App\Models\User $user
     * @param \App\Models\Upload $upload
     * @return int user's used_bytes
     */
    public function completeAndReturnUsedBytes(User $user, Upload $upload): int
    {
        $maxFileSizeToScan = config('filesystems.max_file_size_to_scan');
        $maxUploadSizeToMerge = config('filesystems.max_file_size_to_merge');

        $disk = Storage::disk($upload->disk);
        $fileDirectoryPath = "files/{$upload->uuid}";
        $fileName = $this->fileStorageService->generateStorageName($upload->extension);
        $fileThumbnailName = null; // Placeholder, will be set if upload has a thumbnail.

        $userCacheLock = Cache::lock("user:{$user->id}:update", config('cache.cache_lock_duration'));

        try {
            if (!$disk->exists($fileDirectoryPath)) {
                $disk->makeDirectory($fileDirectoryPath);
            }

            // Move thumbnail
            if ($disk->exists("uploads/{$upload->uuid}/thumbnail.jpeg")) {
                $fileThumbnailName = $this->fileStorageService->generateThumbnailStorageName();

                $disk->move("uploads/{$upload->uuid}/thumbnail.jpeg", "files/{$upload->uuid}/{$fileThumbnailName}");
            }

            // Merge chunks if the file size is smaller than maxUploadSizeToMerge, otherwise we will merge in queue later
            if ($upload->bytes_size <= $maxUploadSizeToMerge) {
                $this->fileStorageService->mergeChunks($upload, $fileName);
            }

            $userCacheLock->block(config('cache.cache_lock_timeout'));

            return DB::transaction(function () use ($fileName, $fileThumbnailName, $maxFileSizeToScan, $maxUploadSizeToMerge, $upload, $user) {
                        $user = User::where('id', $user->id)->lockForUpdate()->first();

                        $userPlan = $this->authService->getUserPlan($user);

                        // Get total new user's used_bytes
                        $newUsedBytes = $user->used_bytes + $upload->bytes_size;

                        // Validate user's used_bytes
                        if ($newUsedBytes > $userPlan->plan->limit_bytes) {
                            throw ValidationException::withMessages([ // Error code 422
                                'used_bytes' => ['The uploaded file exceeds your remaining storage limit.']
                            ]);
                        }

                        // We do not include thumbnail size in user's used_bytes calculation.
                        // Since it's generated by us and usually small in size.
                        $user->update(['used_bytes' => $newUsedBytes]);

                        if ($upload->bytes_size <= $maxUploadSizeToMerge) {
                            $fileStatus = 'completed';
                        } else { // Mark as processing; Dispatch a queue to merge the chunks
                            $fileStatus = 'processing';
                        }

                        $file = File::create([
                                    'uuid' => $upload->uuid,
                                    'status' => $fileStatus,
                                    'visibility' => 'private',
                                    'user_id' => $user->id,
                                    'thumbnail_name' => $fileThumbnailName,
                                    'storage_name' => $fileName,
                                    ...$upload->only(['category', 'disk', 'extension', 'mime_type', 'name', 'duration', 'bytes_size'])
                                ]);

                        $upload->update(['status' => 'completed']);

                        $user->activities()->create(['action' => 'upload', 'file_id' => $file->id]);

                        /**
                         * Dispatch a job to scan the file if the file size is smaller than maxFileSizeToScan, and we can merge the chunks immediately (file size smaller than maxUploadSizeToMerge)
                         * We also can add delay here, in case user suddenly permanently delete the file after upload, to save some unnecessary processing and reduce server load.
                         */
                        if ($upload->bytes_size <= $maxUploadSizeToMerge && $upload->bytes_size <= $maxFileSizeToScan) {
                            FileScan::dispatch($file)
                                    ->onQueue('high')
                                    // ->delay(0)
                                    ->afterCommit();
                        }

                        /**
                         * Dispatch a job to merge the chunks if the file size is larger than maxUploadSizeToMerge
                         * Chain a job to scan the file after merging
                         */
                        if ($upload->bytes_size > $maxUploadSizeToMerge) {
                            FileMergeChunks::dispatch($file)
                                            ->onQueue('high')
                                            ->chain([
                                                new FileScan($file)
                                            ])
                                            ->afterCommit();
                        }

                        return $newUsedBytes;
                    });
        } catch (Exception $e) {
            report($e);

            $upload->update(['status' => 'failed']);

            // Remove files storage (just in case)
            $disk->deleteDirectory($fileDirectoryPath);

            throw $e;
        } finally {
            $userCacheLock?->release();
        }
    }
}
